/** คำอธิบายชื่อฟิลด์เป็นภาษาไทย สำหรับฟอร์มแก้ไขข้อมูล */
export const fieldLabels: Record<string, string> = {
  id: 'รหัสรายการ (id)',
  nameTh: 'ชื่อภาษาไทย',
  nameEn: 'ชื่อภาษาอังกฤษ',
  scientific: 'ชื่อวิทยาศาสตร์',
  pathogen: 'เชื้อสาเหตุ',
  kind: 'ประเภท',
  aliases: 'ชื่อเรียกอื่น',
  localNames: 'ชื่อท้องถิ่น',
  severity: 'ระดับความรุนแรง (low / medium / high / critical)',
  summary: 'สรุปสั้น 1 บรรทัด',
  identify: 'จุดสังเกต',
  symptoms: 'อาการที่มองเห็น',
  distinguish: 'วิธีแยกจากที่คล้ายกัน',
  conditions: 'สภาพแวดล้อมที่ทำให้เกิด',
  stage: 'ระยะที่พบ',
  damage: 'ความเสียหายในแปลง',
  threshold: 'เกณฑ์ตัดสินใจพ่นสาร',
  season: 'ฤดู / สภาพอากาศที่ระบาด',
  cultural: 'วิธีเขตกรรม',
  biological: 'ชีววิธี',
  chemicals: 'สารป้องกันกำจัด (JSON)',
  warnings: 'ข้อควรระวัง',
  sources: 'แหล่งอ้างอิง (JSON)',
  matchKeywords: 'คำค้นสำหรับจับคู่กับผล AI',
  lossImpact: 'ความเสียหายต่อผลผลิต',
  resistantVarieties: 'พันธุ์ต้านทาน',
  controls: 'ใช้ควบคุมศัตรูพืช',
  maizeSpecific: 'มีคำแนะนำสำหรับข้าวโพดโดยตรง',
  rate: 'อัตราใช้',
  howTo: 'วิธีใช้',
  cautions: 'ข้อควรระวัง',
  group: 'กลุ่ม — วัชพืช: ใบแคบ/ใบกว้าง/กก · สารเคมี: รหัสกลุ่ม IRAC / FRAC / HRAC',
  lifeCycle: 'วงจรชีวิต (ฤดูเดียว / ข้ามปี)',
  frequency: 'ความถี่ที่พบ',
  impact: 'ผลกระทบต่อข้าวโพด',
  herbicides: 'สารกำจัดวัชพืชที่ได้ผล',
  code: 'รหัสพันธุ์',
  cropType: 'ชนิดข้าวโพด',
  hybridType: 'ประเภทพันธุ์',
  org: 'หน่วยงานที่พัฒนา',
  certifiedYear: 'ปีที่รับรอง',
  yield: 'ผลผลิต',
  yieldDrought: 'ผลผลิตสภาพแล้ง',
  maturityDays: 'อายุเก็บเกี่ยว',
  silkingDays: 'อายุออกไหม',
  plantHeight: 'ความสูงต้น',
  earHeight: 'ความสูงฝัก',
  resistance: 'ความต้านทานโรค (JSON)',
  strengths: 'ลักษณะเด่น',
  recommendedFor: 'พื้นที่ที่แนะนำ',
  seedSource: 'แหล่งเมล็ดพันธุ์',
  notes: 'หมายเหตุ',
  nutrient: 'ชื่อธาตุอาหาร',
  symbol: 'สัญลักษณ์ธาตุ',
  color: 'สีประจำธาตุ',
  quickSign: 'จุดสังเกตเร็ว',
  cause: 'สาเหตุ',
  fix: 'วิธีแก้',
  category: 'ประเภทสาร',
  chemClass: 'กลุ่มสารเคมีตามโครงสร้าง',
  mode: 'กลไกการออกฤทธิ์',
  formulations: 'สูตรและความเข้มข้น',
  uses: 'กรณีการใช้ (JSON)',
  timing: 'จังหวะการใช้',
  restricted: 'เป็นสารที่ห้ามใช้',
  restrictedReason: 'เหตุผลที่ห้ามใช้',
};

/** ฟิลด์ที่ควรใช้กล่องข้อความหลายบรรทัด */
export const longTextFields = new Set([
  'summary', 'distinguish', 'conditions', 'stage', 'threshold', 'season',
  'lossImpact', 'impact', 'recommendedFor', 'rate', 'cause', 'fix', 'quickSign', 'org',
  'mode', 'timing', 'restrictedReason',
]);
